package com.hcm.backend_service.v2.enums;

public enum ERole {
    SUPER_ADMIN, GROUP_ADMIN, GROUP_DIRECTOR, HOSPITAL_ADMIN, HOSPITAL_DIRECTOR, SCHEDULE_MANAGER, APPOINTMENT_MANAGER, DOCTOR, PATIENT
}
